CONVERT_TO = helios
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
MUSIC_ENABLE = no
OS_DETECTION_ENABLE = yes
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no
VIM_MODE_ENABLE = yes
